spring:
  application:
    name: spring-ai-text-to-speech-elevenlabs-streaming-response

  # AI configurations
  ai:
    elevenlabs:
      api-key: ${ELEVENLABS_API_KEY:sk_108c80c26f448da2d4595e0733bad08bc6fd4c0b4b38244f}
      tts:
        enableLogging: true
        options:
          model-id: eleven_multilingual_v2
          output-format: mp3


# (Optional) For detailed request/response logging
logging:
  level:
    org.zalando.logbook.Logbook: TRACE